read_task:
  description: >
    Receber receber o caminho {filepath} de um arquivo (PDF, TXT, CSV ou HTML) e extrair seu conteúdo.
  expected_output: >
    O conteúdo do arquivo convertido para um texto legivel.
  agent: reader

analysis_task:
  description: >
    Analisar o conteúdo e identificar os pontos principais do documento.
  expected_output: >
    Uma lista estruturada em markdown com os tópicos principais do documento.
  agent: analyst

write_task:
  description: >
    Criar um resumo conciso contendo a estrutura de tópicos baseado nos principais pontos extraídos.
  expected_output: >
    Um resumo bem estruturado em markdown com os tópicos: Objetivo, Pontos Principais e Conclusão.
    O objetivo descreve o objetivo principal do texto.
    Principais tópicos contêm as partes de maior relevância do documento.
    Conclusão é um rápido resumo sobre todos os pontos abordados no texto.
  agent: writer